name: places
description: "Widgets Stack, Column, Row, Container, Text y Icon"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Regular.ttf
